#pragma once

#define IOCTL_DELETEPROTECTOR_ADD_EXE	\
	CTL_CODE(0x8000, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DELETEPROTECTOR_REMOVE_EXE	\
	CTL_CODE(0x8000, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DELETEPROTECTOR_CLEAR		\
	CTL_CODE(0x8000, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_DELETEPROTECTOR_ADD_DIR	\
	CTL_CODE(0x8000, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DELETEPROTECTOR_REMOVE_DIR	\
	CTL_CODE(0x8000, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DELETEPROTECTOR_CLEAR_DIRS		\
	CTL_CODE(0x8000, 0x805, METHOD_NEITHER, FILE_ANY_ACCESS)
