#pragma once

#define IOCTL_DELETEPROTECTOR_ADD_EXE	\
	CTL_CODE(0x8000, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DELETEPROTECTOR_REMOVE_EXE	\
	CTL_CODE(0x8000, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DELETEPROTECTOR_CLEAR		\
	CTL_CODE(0x8000, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
